### ISSUE TITLE
Gen2 commandline not working

### ISSUE THREAD

**Issue by JangoBritt** [nschum/homebridge-twinkly#2] opened 2019-12-07 21:19 UTC
I’m trying to control my gen2 250 string with the command line and get the below error. 

Homebridge switch works fine in HomeKit, but can’t use —mode on or off, or any of the effect names in commandline

Fw ver 2.4.16

```
Authentication…
POST http://192.168.1.75/xled/v1/login
{ authentication_token: 'JTvLYqveHzE=',
  authentication_token_expires_in: 14400,
  'challenge-response': 'b8140cb4be6218e66113a6f9e2b8d7423e7fea73',
  code: 1000 }
POST http://192.168.1.75/xled/v1/verify
{ code: 1000 }
Authentication successful
GET http://192.168.1.75/xled/v1/gestalt
{ product_name: 'Twinkly',
  hardware_version: '100',
  bytes_per_led: 3,
  hw_id: 'f4ce84',
  flash_size: 64,
  led_type: 14,
  product_code: 'TWS250STP-B',
  fw_family: 'F',
  device_name: 'Xmas Tree',
  uptime: '7213534',
  mac: '24:6f:28:f4:ce:85',
  uuid: 'C498B133-B544-4A88-B11B-E2197A937682',
  max_supported_led: 1020,
  number_of_led: 250,
  led_profile: 'RGB',
  frame_rate: 23.81,
  movie_capacity: 992,
  copyright: 'LEDWORKS 2018',
  code: 1000 }
(node:19257) UnhandledPromiseRejectionWarning: unknown color format undefined
(node:19257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19257) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mensa84** [comment] 2019-12-08 06:12
I have the same firmware version and getting exactly the same error!
I am able to turn off my Twinkly Gen 2 LED 250 by command line tool and HomeKit, but I am not able to turn it on.

Could you please fix that problem?

**Comment by sebiprinz** [comment] 2019-12-15 12:26
I cannot even turn off my Twinkly Gen 2 LED 250 lights.

> twinkly --ip 192.168.0.25 --mode off
Authentication…
POST http://192.168.0.25/xled/v1/login
{
  authentication_token: 'l1CwaBdKKlY=',
  authentication_token_expires_in: 14400,
  'challenge-response': 'b2182c8cfb16900605a8f18426cf6013b76024f9',
  code: 1000
}
POST http://192.168.0.25/xled/v1/verify
{ code: 1000 }
Authentication successful
GET http://192.168.0.25/xled/v1/gestalt
{
  product_name: 'Twinkly',
  hardware_version: '100',
  bytes_per_led: 4,
  hw_id: '18d4dc',
  flash_size: 64,
  led_type: 12,
  product_code: 'TWS250SPP-B',
  fw_family: 'G',
  device_name: 'Twinkly_18D4DD',
  uptime: '5970934',
  mac: '24:6f:28:18:d4:dd',
  uuid: '9119DCDA-C2F3-4D68-AE0D-BE625ABA5DD0',
  max_supported_led: 510,
  number_of_led: 250,
  led_profile: 'RGBW',
  frame_rate: 27.78,
  movie_capacity: 1984,
  copyright: 'LEDWORKS 2018',
  code: 1000
}
(node:2193) UnhandledPromiseRejectionWarning: unknown color format undefined
(node:2193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The Alexa skill is also not working, maybe the problem is on Twinkly's end.

**Comment by nschum** [comment] 2019-12-20 17:52
Hi everybody. Sorry, I never tested without specifying an explicit color. This should be fixed with #3. Thanks @drewcovi.

**Closed by nschum** 2019-12-20 17:52 UTC

**Comment by drewcovi** [comment] 2019-12-20 18:29
That’s how we roll in this community 😎

**Comment by mensa84** [comment] 2019-12-20 20:01
Does this mean, that there is already a release which fixes that problem, or will there be one soon?
